### PR TITLE
fix: Fetch repositories

### PR DESCRIPTION
**Pull request by saundefined**
Currently, only 100 repositories are requested.
After adding doc-* repositories, there are more of them.

The repositories of the next pages are also loaded in the list and sorted by update

### CODE REVIEW

**Comment by cmb69** [comment]
Ah, good catch! Still, I'm somewhat concerned about the performance; building that list is already quite slow.

**Comment by saundefined** [comment]
@cmb69, thanks for the feedback! 
What do you think of this change?

Instead of automatically loading the next repositories, add a button to load more.

**Comment by cmb69** [comment]
Oh, just noticed that this is about qa.php.net (I though it is about bugs.php.net). I haven't used that interface for years, but apparently performance is not really an issue there, so maybe just go with the first commit?

**Comment by saundefined** [comment]
Sure, reverted :)

**Comment by saundefined** [comment]
Feature removed in e4fa7d2

**Pull request closed without merging**
